<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1hnnCtn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1hnnCtn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1hnnCtn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1hnnCtn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1hnnCtn\App_KernelDevDebugContainer([
    'container.build_hash' => '1hnnCtn',
    'container.build_id' => '3cfe722f',
    'container.build_time' => 1613639362,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1hnnCtn');
