<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1EhLki6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1EhLki6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1EhLki6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1EhLki6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1EhLki6\App_KernelDevDebugContainer([
    'container.build_hash' => '1EhLki6',
    'container.build_id' => '3d9ce9ef',
    'container.build_time' => 1613633935,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1EhLki6');
