<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCc8I95w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCc8I95w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCc8I95w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCc8I95w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCc8I95w\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cc8I95w',
    'container.build_id' => '6d77e13d',
    'container.build_time' => 1613574724,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCc8I95w');
